### PR TITLE
Basic Llama2 Tuning

### PR DESCRIPTION
**Pull request by tengomucho**
# What does this PR do?

Add support for Llama model tuning on TPU v5e, with a related example.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by alanwaketan** [comment]
Is there any reasons why you choose to use 2D sharding instead of FSDPv2? The latter is integrated in to transformer trainer: https://huggingface.co/blog/gemma-peft#accelerate-with-fsdp-via-spmd-on-tpu

**Comment by tengomucho** [comment]
@alanwaketan yes, the reason is that it did not work out of the box, apparently the trainer was trying to use some API from the XLA that was in experimental and it is not available anymore, so the code was raising an exception. I guess we can fix the FSDP in transformers too, and compare both to see which one performs better.

**Comment by alanwaketan** [comment]
> @alanwaketan yes, the reason is that it did not work out of the box, apparently the trainer was trying to use some API from the XLA that was in experimental and it is not available anymore, so the code was raising an exception. I guess we can fix the FSDP in transformers too, and compare both to see which one performs better.

Can you point me to the error? All the API the trainer uses should be available in 2.3.

**Comment by alanwaketan** [comment]
FSDPv2's intention is to releif the need for all this complicated shardings from regular users. Unless you know you need 2D sharding instead of 1D.

**Comment by tengomucho** [comment]
@alanwaketan sure it makes total sense, I will get back to you with the error

**Comment by tengomucho** [comment]
@alanwaketan you can check the errors I see with FSDP [here](https://gist.github.com/tengomucho/3e6b56cb09148aa32623e82855303934).

**Comment by tengomucho** [comment]
I raised an issue on the `accelerate` project to fix the FSDP/dataloader issue https://github.com/huggingface/accelerate/issues/2775

**Comment by alanwaketan** [comment]
> @alanwaketan Ah btw I was still using torch xla 2.2, we haven't moved to 2.3 yet. I will do that so I can re-test FSDP.

2.2 is expected to not work. The 2.3 issue seems more generic than FSDPv2.

**Review by mfuntowicz — APPROVED** [review]
LGTM! 🔥

**Pull request merged**
